-- Fix security vulnerability: ONLY allow users to insert logs where actor_id matches their own auth.uid().
-- This prevents forged audit logs.
-- System logs generated by RPCs (SECURITY DEFINER) bypass this check, which is intentional.

BEGIN;

DROP POLICY IF EXISTS "Anyone can insert audit logs" ON public.system_audit_log;
DROP POLICY IF EXISTS "Authenticated users can insert own audit logs" ON public.system_audit_log;

CREATE POLICY "Authenticated users can insert own audit logs"
ON public.system_audit_log FOR INSERT
TO authenticated
WITH CHECK (actor_id = auth.uid());

COMMIT;

NOTIFY pgrst, 'reload schema';
